Category.create!([
  {name: "Clothing"},
  {name: "Cookware and Filtration"},
  {name: "Electronics"},
  {name: "Toiletries"},
  {name: "Repair and Med Kit"},
  {name: "Shoes"},
  {name: "Misc."},
  {name: "Shelter and Sleep System"},
  {name: "Big 3 + Sleep Pad"}
])
CategoryJoin.create!([
  {category_id: 22, gear_id: 2},
  {category_id: 22, gear_id: 3},
  {category_id: 21, gear_id: 7},
  {category_id: 22, gear_id: 8},
  {category_id: 27, gear_id: 9},
  {category_id: 27, gear_id: 10},
  {category_id: 26, gear_id: 11},
  {category_id: 29, gear_id: 1},
  {category_id: 29, gear_id: 6},
  {category_id: 29, gear_id: 13},
  {category_id: 29, gear_id: 19},
  {category_id: 29, gear_id: 22},
  {category_id: 29, gear_id: 12},
  {category_id: 23, gear_id: 106},
  {category_id: 24, gear_id: 107},
  {category_id: 24, gear_id: 108},
  {category_id: 29, gear_id: 14},
  {category_id: 23, gear_id: 113},
  {category_id: 25, gear_id: 114},
  {category_id: 24, gear_id: 115},
  {category_id: 26, gear_id: 128},
  {category_id: 29, gear_id: 129},
  {category_id: 29, gear_id: 131},
  {category_id: 21, gear_id: 135},
  {category_id: 21, gear_id: 136},
  {category_id: 21, gear_id: 137},
  {category_id: 23, gear_id: 138},
  {category_id: 25, gear_id: 139},
  {category_id: 21, gear_id: 140},
  {category_id: 23, gear_id: 141},
  {category_id: 26, gear_id: 142},
  {category_id: 22, gear_id: 143},
  {category_id: 29, gear_id: 144},
  {category_id: 22, gear_id: 145},
  {category_id: 21, gear_id: 147},
  {category_id: 24, gear_id: 148},
  {category_id: 24, gear_id: 149},
  {category_id: 22, gear_id: 150},
  {category_id: 21, gear_id: 151},
  {category_id: 22, gear_id: 152},
  {category_id: 22, gear_id: 153},
  {category_id: 21, gear_id: 154},
  {category_id: 24, gear_id: 155}
])
Gear.create!([
  {item_name: "Hiking Pants", item_description: "Adjustable hiking pants. Can be shorts or pants", item_weight: 13.6, item_quantity: 1, item_url: ""},
  {item_name: "Charging Block", item_description: "Portable charging block", item_weight: 8.0, item_quantity: 1, item_url: ""},
  {item_name: "Black Diamond Trail Ergo Cork", item_description: "Trekking poles with aluminum shaft, cork handles, and an external lever lock.", item_weight: 18.0, item_quantity: 1, item_url: nil},
  {item_name: "HOKA ONE Speedgoat", item_description: "Durable trail running shoes with a 4mm heel-to-toe drop.", item_weight: 21.6, item_quantity: 1, item_url: nil},
  {item_name: "ULA Circuit", item_description: "Pack capable of carrying up to 68L and 35 lbs.", item_weight: 31.0, item_quantity: 1, item_url: nil},
  {item_name: "REI Co-op Magma 15", item_description: "Sleeping bag capable of keeping the user warm in tempeartures as low as 16 degrees.", item_weight: 28.2, item_quantity: 1, item_url: nil},
  {item_name: "Med Kit", item_description: "Med-Kit suitable for 2 people", item_weight: 17.0, item_quantity: 1, item_url: ""},
  {item_name: "Cheap Toothbrush", item_description: "An incredibly cheap toothbrush with the end cut off to save weight!", item_weight: 2.0, item_quantity: 1, item_url: ""},
  {item_name: "Therm-a-rest NeoAir XLite", item_description: "Lightweight insulated sleeping pad ", item_weight: 18.0, item_quantity: 1, item_url: nil},
  {item_name: "Montbell Versatile", item_description: "Shell (rain jacket) includes inside pockets.", item_weight: 8.0, item_quantity: 1, item_url: nil},
  {item_name: "FujiFilm Xt30 ", item_description: "Camera", item_weight: 16.0, item_quantity: 1, item_url: ""},
  {item_name: "Huge band-aid collection", item_description: "Tons of band-aids for scrapes and cuts", item_weight: 8.0, item_quantity: 1, item_url: ""},
  {item_name: "Lightweight Sandals", item_description: "Perfect camp shoe, lightweight and comfortable", item_weight: 6.0, item_quantity: 1, item_url: ""},
  {item_name: "Zpacks ArcHaul", item_description: "Lightweight Pack", item_weight: 28.0, item_quantity: 1, item_url: "https://zpacks.com/products/arc-haul-backpack"},
  {item_name: "Darn Tough Socks ", item_description: "Durable wool socks", item_weight: 2.3, item_quantity: 2, item_url: ""},
  {item_name: "Toothpaste", item_description: "Bio Friendly toothpaste. Keeping teeth clean!!", item_weight: 4.0, item_quantity: 1, item_url: ""},
  {item_name: "Functional Spork/Knife", item_description: "A great all around utensil", item_weight: 3.0, item_quantity: 1, item_url: ""},
  {item_name: "SOTO Windmaster", item_description: "Lightweight stove.", item_weight: 6.0, item_quantity: 1, item_url: nil},
  {item_name: "Sawyer Squeeze", item_description: "Water filter. Effectively removes 99.8% of bacteria from water.", item_weight: 6.0, item_quantity: 1, item_url: nil},
  {item_name: "Bearikade Weekender", item_description: "Bear canister made of carbon fiber. Shield from the bears!", item_weight: 31.0, item_quantity: 2, item_url: nil},
  {item_name: "Smart Water Bottle", item_description: "lightweight bottle 32 oz.", item_weight: 1.0, item_quantity: 1, item_url: ""},
  {item_name: "Super nice Stove", item_description: "Stove", item_weight: 13.0, item_quantity: 1, item_url: ""},
  {item_name: "Soap ", item_description: "clean bar of soap", item_weight: 6.0, item_quantity: 1, item_url: ""},
  {item_name: "Zpacks Duplex", item_description: "Lightweight Tent. Very Durable.", item_weight: 20.75, item_quantity: 2, item_url: "https://zpacks.com/products/duplex-tent"},
  {item_name: "Zpacks 10 Degree Down Sleeping Bag", item_description: "Sleeping bag", item_weight: 22.7, item_quantity: 1, item_url: nil},
  {item_name: "Big Agnes TigerWall UL3", item_description: "A tent for 3. Lightweight and compact.", item_weight: 33.6, item_quantity: 1, item_url: "https://www.rei.com/product/128991/big-agnes-tiger-wall-ul3-tent"}
])
Pack.create!([
  {user_id: 3, gear_id: 1},
  {user_id: 3, gear_id: 2},
  {user_id: 3, gear_id: 3},
  {user_id: 3, gear_id: 6},
  {user_id: 3, gear_id: 7},
  {user_id: 3, gear_id: 8},
  {user_id: 3, gear_id: 9},
  {user_id: 3, gear_id: 10},
  {user_id: 3, gear_id: 11},
  {user_id: 3, gear_id: 12},
  {user_id: 3, gear_id: 13},
  {user_id: 2, gear_id: 14},
  {user_id: 2, gear_id: 19},
  {user_id: 2, gear_id: 47},
  {user_id: 2, gear_id: 50},
  {user_id: 2, gear_id: 59},
  {user_id: 2, gear_id: 67},
  {user_id: 2, gear_id: 73},
  {user_id: 2, gear_id: 75},
  {user_id: 5, gear_id: 1},
  {user_id: 5, gear_id: 2},
  {user_id: 5, gear_id: 3},
  {user_id: 5, gear_id: 6},
  {user_id: 5, gear_id: 7},
  {user_id: 5, gear_id: 8},
  {user_id: 5, gear_id: 9},
  {user_id: 5, gear_id: 10},
  {user_id: 5, gear_id: 11},
  {user_id: 5, gear_id: 12},
  {user_id: 5, gear_id: 13},
  {user_id: 5, gear_id: 14},
  {user_id: 5, gear_id: 19},
  {user_id: 5, gear_id: 22},
  {user_id: 4, gear_id: 78},
  {user_id: 3, gear_id: 81},
  {user_id: 3, gear_id: 84},
  {user_id: 3, gear_id: 85},
  {user_id: 3, gear_id: 86},
  {user_id: 3, gear_id: 88},
  {user_id: 3, gear_id: 89},
  {user_id: 3, gear_id: 90},
  {user_id: 3, gear_id: 91},
  {user_id: 3, gear_id: 92},
  {user_id: 3, gear_id: 93},
  {user_id: 3, gear_id: 94},
  {user_id: 3, gear_id: 95},
  {user_id: 3, gear_id: 96},
  {user_id: 3, gear_id: 97},
  {user_id: 3, gear_id: 98},
  {user_id: 3, gear_id: 99},
  {user_id: 2, gear_id: 100},
  {user_id: 2, gear_id: 101},
  {user_id: 3, gear_id: 102},
  {user_id: 3, gear_id: 103},
  {user_id: 3, gear_id: 104},
  {user_id: 3, gear_id: 106},
  {user_id: 3, gear_id: 107},
  {user_id: 3, gear_id: 108},
  {user_id: 3, gear_id: 109},
  {user_id: 3, gear_id: 110},
  {user_id: 3, gear_id: 111},
  {user_id: 3, gear_id: 112},
  {user_id: 3, gear_id: 113},
  {user_id: 3, gear_id: 114},
  {user_id: 3, gear_id: 115},
  {user_id: 3, gear_id: 131},
  {user_id: 3, gear_id: 135},
  {user_id: 3, gear_id: 136},
  {user_id: 3, gear_id: 137},
  {user_id: 3, gear_id: 138},
  {user_id: 3, gear_id: 139},
  {user_id: 3, gear_id: 140},
  {user_id: 3, gear_id: 141},
  {user_id: 3, gear_id: 142},
  {user_id: 3, gear_id: 143},
  {user_id: 3, gear_id: 144},
  {user_id: 3, gear_id: 145},
  {user_id: 3, gear_id: 146},
  {user_id: 3, gear_id: 147},
  {user_id: 3, gear_id: 148},
  {user_id: 3, gear_id: 149},
  {user_id: 3, gear_id: 150},
  {user_id: 3, gear_id: 151},
  {user_id: 3, gear_id: 152},
  {user_id: 2, gear_id: 153},
  {user_id: 2, gear_id: 154},
  {user_id: 3, gear_id: 155}
])
User.create!([
  {email: "sydstewart@example.com", password_digest: "$2a$12$KgDtXN1XOXz1Ds3f/LAfbuaq3wklyIuQH9F5ncfn9MgBJil8Weelu", name: "Syd Stewart"},
  {email: "zackborges@example.com", password_digest: "$2a$12$Ckm4qph74YBvFz6qlG9C5eXbI3vECGTFbOIJ.Sv/uNT1JhjwODNbu", name: "Zack Borges"},
  {email: "rexryan@example.com", password_digest: "$2a$12$H20NCsNAQDA82yc8AzYex.DOfYWW6z.5D3ch14JyMIlHYa0UHXopW", name: "Rex Ryan"},
  {email: "example@example.com", password_digest: "$2a$12$YRHFiJnNn6qWz8u40gBL/OatUz/0ZRax4GJaTjKck7ZowtrjIqFim", name: "example gear"},
  {email: "steve@example.com", password_digest: "$2a$12$1YwBLvkK3ZVGCrEhhRLDKO0RIvA7uDgcYCj91Q8MOyK/MQP/0YYbK", name: "Steve"},
  {email: "hello@example.com", password_digest: "$2a$12$tKJfgevMD3ACuLXqVBzodecsXovl.BZbN1T5fuQhX66uEU3xjgZxC", name: "hello"},
  {email: "johnny@example.com", password_digest: "$2a$12$4QpemYBuXW6atvnS0FnlzOHTIJJzAK1lm3aGczLtqm50Q443WTjsW", name: "Johnny Cash"},
  {email: "jay@example.com", password_digest: "$2a$12$h2xIZxr4pC2oLwrQu3M9suM.yYQ0ZAk15k8coav/HvrkrECB2auvS", name: "Jay"}
])
